-- Script PostgreSQL
-- Curso de Tópicos Avanzados de base de datos - UPB 202320
-- Samuel Pérez Hurtado ID 000459067 - Luisa María Flórez Múnera ID 000449529

-- Proyecto: Sistema de gestión de recursos humanos y empleos en la industria tecnológica en los años 2020, 2021 y 2022
-- Motor de Base de datos: Oracle XE 21c (Trabajado por Samuel Pérez Hurtado)

-- Tener presente el contenedor al que está conectado
alter session set container=xepdb1;

-- USER SQL
CREATE USER "GESTION_RRHH_TECH_USR" IDENTIFIED BY "gestion_rrhh"  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "GESTION_RRHH_TECH_USR";
GRANT ALTER SESSION TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT ALTER ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT COMMENT ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT READ ANY TABLE TO "GESTION_RRHH_TECH_USR";

GRANT SELECT ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT INSERT ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT UPDATE ANY TABLE TO "GESTION_RRHH_TECH_USR";
GRANT DELETE ANY TABLE TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY VIEW TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY VIEW TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY INDEX TO "GESTION_RRHH_TECH_USR";
GRANT ALTER ANY INDEX TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY INDEX TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY TRIGGER TO "GESTION_RRHH_TECH_USR";
GRANT ALTER ANY TRIGGER TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY TRIGGER TO "GESTION_RRHH_TECH_USR";

GRANT ALTER ANY PROCEDURE TO "GESTION_RRHH_TECH_USR";
GRANT CREATE ANY PROCEDURE TO "GESTION_RRHH_TECH_USR";
GRANT DEBUG ANY PROCEDURE TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY PROCEDURE TO "GESTION_RRHH_TECH_USR";
GRANT EXECUTE ANY PROCEDURE TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY SEQUENCE TO "GESTION_RRHH_TECH_USR";
GRANT ALTER ANY SEQUENCE TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY SEQUENCE TO "GESTION_RRHH_TECH_USR";
GRANT SELECT ANY SEQUENCE TO "GESTION_RRHH_TECH_USR";

GRANT CREATE ANY MATERIALIZED VIEW TO "GESTION_RRHH_TECH_USR";
GRANT ALTER ANY MATERIALIZED VIEW TO "GESTION_RRHH_TECH_USR";
GRANT DROP ANY MATERIALIZED VIEW TO "GESTION_RRHH_TECH_USR";

GRANT SELECT ANY DICTIONARY TO "GESTION_RRHH_TECH_USR";

-- Creamos el esquema inicial
CREATE USER "GESTION_RRHH_TECH_INICIAL" IDENTIFIED BY "gestion_rrhh"  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
ALTER USER "GESTION_RRHH_TECH_INICIAL" QUOTA UNLIMITED ON USERS;

-- Creamos el esquema optimizado
CREATE USER "GESTION_RRHH_TECH_OPTIMIZADO" IDENTIFIED BY "gestion_rrhh"  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
ALTER USER "GESTION_RRHH_TECH_OPTIMIZADO" QUOTA UNLIMITED ON USERS;

-- Privilegios específicos para el esquema optimizado
GRANT CREATE TABLE TO "GESTION_RRHH_TECH_OPTIMIZADO";